### Get news for company from google news
GET http://localhost:3000/news?company=openai

### Scrape article
GET http://localhost:3000/news/scrape?url=https://runwayml.com/blog/

### Scrape article Scalability AI
GET http://localhost:3000/news/scrape?url=https://blog.perplexity.ai/


### Get latest date for company
GET http://localhost:3000/news/latest?company=runwayml